### ISSUE TITLE
Handle http *AND* https for resolve absolute/relative

### ISSUE THREAD

**Issue by basti1302** [basti1302/traverson#22]
See TODO/FIXME in https://github.com/basti1302/traverson/blob/master/lib/walker.js

**Comment by xogeny** [comment]
FYI, I came across this issue while reviewing the source code.  What you really need is this:

https://github.com/medialize/URI.js

It handles this case.  What you are doing there is just:

```
    URI(url, base).toString()
```

...using that library.  The point here is that what you really need is something that implements [RFC 3986](https://tools.ietf.org/html/rfc3986#section-5.1).  I think including `URI.js` would not only give you this, but I think it would also eliminate a dependency on `resolve-url` and `url-template` (using [this](http://medialize.github.io/URI.js/uri-template.html).  In other words, you could actually replace those two with just this *and* gain functionality in the process.

Of course, you are building all this off of Node.js.  So please note that `uri.js` in `npm` is NOT https://github.com/medialize/URI.js.  Instead, you want [URIjs](https://www.npmjs.com/package/URIjs).

Then again, it might be possible to use `resolve-url` to do this.  I can't really tell from the documentation.  It seems to want to leverage `window.location` which seems like it could be annoying and/or dangerous if your resolutions have nothing to do with the browser.

**Comment by basti1302** [comment]
a fix has been published with 1.0.0
