### ISSUE TITLE
How to deal with linked forms?

### ISSUE THREAD

**Issue by ashic** [basti1302/traverson#24]
I'm looking into Traverson (looks awesome), and have run into an issue that I can't figure out how to solve.

Say, we have a resource that's a form with links to submit. Let's say, /api/doggies/registration-form gives us this:

{ name: '', age:'', site_zone: 'uk', _links : {'self': /api/doggies/registration-form }}

We've got this resource via:
var api = traverson.jsonHal.from('/api');
api.newRequest().withRequestOptions(...).follow('doggies', 'registration-form').getResource(
    function(e, doc) {
       //the json above is in doc.
    }
)

Now doc is a representation of the registration form. It has two values the client needs to fill in (name and age), and another that is relevant to the server and should be copied over verbatim in the submitted data. The "doc" is json that's essentially the new resource. It's got a link to post to, and data payload that the client should update before posting.

Without creating a new traverson.jsonHAL.from(theSelfLink), is there a way I can take the "doc", update the values, and post? Perhaps what I'm looking for is in the lines of:

 var api = traverson.jsonHal.from('/api');
api.newRequest().withRequestOptions(...).follow('doggies', 'registration-form').getResource(
    function(e, doc) {
       //the json above is in doc.
         doc.name = "Scooby";
         doc.age = 11;
         doc.post("self", function(err, res){}); // or something.post(doc, "self")
    }
)

The emphasis here being that we need to be able to take a server generated form, update the fields we care about, but submit the whole thing so the server is free to add fields in the future.

If we could simply take some json and create a traverson resource, this should "just work". How can we do that?

**Comment by basti1302** [comment]
I already started to work continuing traversals in [this branch](https://github.com/basti1302/traverson/tree/continue-traversal) (better late than never, right? ;-) ). I'd love some feedback on the API (which is work in progress right now), so chime in to the discussion at issue #40 if you like.

**Comment by basti1302** [comment]
Continuing link traversals has landed in 2.0.0, which should also enable the use case described in this issue.
