### ISSUE TITLE
Setting X-Requested-With header adds CORS requirements

### ISSUE THREAD

**Issue by jtatum** [basti1302/traverson#26]
Traverson sets the X-Requested-With header on all requests to XMLHttpRequest. Not a big deal, except this makes browsers a little stricter. Even on a GET request, they'll poll the server first with OPTIONS, and the response to OPTIONS must have an Access-Control-Allow-Headers value set to explicitly allow the header in question.

I was confused about why my browser started sending OPTIONS to the server (and getting 500 errors). This is why.

**Comment by basti1302** [comment]
I'm using superagent for XHR when Traverson is running in the browser. It seems superagent used this header for a while, but later versions do not send this header anymore (See https://github.com/visionmedia/superagent/issues/189 )   I just updated the superagent version locally and the header was gone.

This fix will be included in the next version (1.0.0). Unfortunately it may take a few days/weeks until I can publish it - it has some other major changes in it, which are not completely finished.

**Comment by basti1302** [comment]
If you need a fix immediately, you could clone this repo, update the superagent.js file in browser/lib/third-party, run `npm install` and `grunt` and use the files from browser/dist.

**Comment by jtatum** [comment]
Thank you so much! It actually helped me update my backend server to handle more CORS stuff, so it all worked out. No rush from me. Feel free to close this issue whenever.

**Comment by basti1302** [comment]
this was published with 1.0.0
