### ISSUE TITLE
not handling errors in request.js

### ISSUE THREAD

**Issue by luigibozzo** [basti1302/traverson#28]
I'm not getting error callback when OPTIONS call for a CORS request fails.

I applied a fix to request.js to catch errors.

I have modified the function below.

Request.prototype.get = function(uri, callback) {
  mapRequest(superagent.get(uri), this.options)
    .end(function(response) {
    callback(null, mapResponse(response));  
  });
};

as  

Request.prototype.get = function(uri, callback) {
  mapRequest(superagent.get(uri), this.options)
    .end(handleResponse(callback));
};
var handleResponse = function(callback) {
  return function(error, data) {
   if (error) {
      return callback(error);
    } else {
      return callback(null, mapResponse(data));
    }
  };
};

**Comment by basti1302** [comment]
Would you mind sending the modification as a pull request?

**Comment by xogeny** [comment]
I've created a PR for this at: https://github.com/basti1302/traverson/pull/35

NOTE that it not only tries to address the issue with `get`, but it also modifies `del`, `post`, `put` and `patch` as well.

**Comment by basti1302** [comment]
I'll close this issue for now. Futher discussion (if needed) should happen in #35.
