### ISSUE TITLE
How to reconfigure this package to use GET instead of OPTIONS when getting resources?

### ISSUE THREAD

**Issue by binarykitchen** [basti1302/traverson#29]
The API endpoint I'd like to interact with, does not support the OPTIONS method (returns 404). So, how can I tell traverson to use GET instead?

**Comment by binarykitchen** [comment]
Ah, this one is the cause
https://github.com/basti1302/traverson/issues/26

**Comment by basti1302** [comment]
I'll close this as a duplicate if you don't mind.
