### ISSUE TITLE
Request options get ignored / overwritten

### ISSUE THREAD

**Issue by binarykitchen** [basti1302/traverson#31]
It looks like that when I do

```js
            .withRequestOptions({headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                'Accept':       'application/json, text/plain, */*'
            }})
```

then these get ignored when passed onto superagent :(

**Comment by binarykitchen** [comment]
To be exact, the above problem occurs when doing a POST thing:

```js
    this.postOrder = function(order) {
        return makeRequest()
            .follow('orders')
            .withRequestOptions({headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                'Accept':       'application/json, text/plain, */*'
            }})
            .post(order)
    }
```

Looking in the console, it seems that the content type of `'application/x-www-form-urlencoded'` is set for the GET request but not for the POST request. In my case, I only want to set the options for the POST request but leaving the GET options untouched. How can we do this?

**Comment by basti1302** [comment]
I'm currently knee deep in some other projects. This is why work on Traverson has come to a halt for the last two months. I'll start working on Traverson again soon (~2 weeks) and will have a look at it then. Sorry for the delay.

**Comment by basti1302** [comment]
I had a closer look at this. The answer is three-fold and not yet complete:

1) Setting HTTP headers/request options *only* for the POST request, without setting them for the preceding GET requests is not possible, currently. There is already an open issue (#25) that describes this problem. I'm not sure if it makes it into the next release, but it's quite high on my list.
2) Generally HTTP headers/request options are also included used with the POST request. See the added test in 5b132aa.
3) You're case is special because you are setting the Content-Type to something different than `application/json`. Somewhere somehow the Content-Type header gets overwritten with `application/json`, I am not yet sure where and why.

**Comment by basti1302** [comment]
Note to self: There is a git stash that has a test for this problem.

**Comment by basti1302** [comment]
Update:
1) Setting HTTP headers only for a single request in the link traversal process has been implemented (see #25)
3) This works now. See https://github.com/basti1302/traverson/blob/master/test/localhost.js#L543-L616 (tests `'should post with x-www-form-urlencoded'` and `'should post form via request options with x-www-form-urlencoded'`) for two alternative ways to post with content type x-www-form-urlencoded. One uses the `header` option field in the request option object, the other uses the `form` field (compare request docs https://github.com/request/request#applicationx-www-form-urlencoded-url-encoded-forms).

Actually, I also tested this against an older Traverson version (84429055e3f59fbcca5be387b56b8c1831f17603) and it also seems to work there, so I am not sure why you saw this behaviour. The test where I 'reproduced' the bug with was borked, I accidentally expected the Accept header to be x-www-form-urlencoded, while I should have checked the Content-Type header.

Anyways, it definitely works now.

**Comment by basti1302** [comment]
Please test again with version 1.1.0

**Comment by binarykitchen** [comment]
Sorry, can't this week ... but respect for your hard work!

**Comment by szxnyc** [comment]
Hello @basti1302 ,

I'm using traverson-angular and traverson-hal versions 5.0.0 and still seem to see this issue.

I tried json(), jsonHal(), useContentNegotiation(), withRequestOptions() to set the media type explicitly. Nothing seems to work.. it always set the Content-Type:application/x-www-form-urlencoded

My backend is erroring out with :

> org.springframework.http.converter.HttpMessageNotReadableException: No suitable HttpMessageConverter found to read request body into object of type class com.test.People from request with content type of application/x-www-form-urlencoded;charset=UTF-8

```
    traverson.registerMediaType(JsonHalAdapter.mediaType, window.JsonHalAdapter);
    traverson
    .from('/api').jsonHal()
    .follow('people')
    .post(body, function(error, response) {
      if (error) {
        console.error('No luck :-)')
      } else {
        console.log('POST request sucessful')
        console.log('HTTP status code: ' + response.statusCode)
      }
    });
```

**Comment by basti1302** [comment]
Sorry about this, but actually this works as (currently) expected. Setting a media type does currently *not* automatically set Accept or Content-Type headers. You can set them manually, however.

There is a discussion over at https://github.com/basti1302/traverson/issues/37 about settings these headers to reasonable defaults when calling jsonHal().

If I get around to do it, I'll implement it some time down the road.

For now your code should look like that:

```
 traverson.registerMediaType(JsonHalAdapter.mediaType, window.JsonHalAdapter);
    traverson
    .from('/api')
    .jsonHal()
    .withRequestOptions({
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      }
    })
    .follow('people')
    ...
```

**Comment by szxnyc** [comment]
@basti1302 Thank you! That works.

Also for those interested here is the rest of the code:

```
traverson
    .from('/api')
    .jsonHal()
    .withRequestOptions({
      headers: {
        'Accept': 'application/hal+json',
        'Content-Type': 'application/hal+json'
      }
    })
    .follow('people')
    .post(body).result.then(function(document){
      $log.info("person created!");
    }, function(err){
      $log.info("person was not created.");
      console.dir(err);
    });
  }
```
