### ISSUE TITLE
Support usage in tests

### ISSUE THREAD

**Issue by deyhle** [basti1302/traverson#34]
I would like to use traverson for my integration tests (of a node.js/express API). 

However, giving traverson an http.Server instance instead of a URI as entry point (similar to [supertest](https://github.com/visionmedia/supertest)) does not work (`undefined is not a function`).

Would be great if you could add support for that. There is, to my knowledge, no HAL testing library for JavaScript out there and traverson would be the perfect fit.

**Comment by basti1302** [comment]
This is outside of the scope of Traverson. You might be able to build something like that on top of traverson or by forking Traverson.
