### ISSUE TITLE
Something is not right here...

### ISSUE THREAD

**Issue by xogeny** [basti1302/traverson#38]
I can submit a PR for this...but I'm not sure what it is supposed to achieve.  The issue can be found at:

https://github.com/basti1302/traverson/blob/master/lib/actions.js#L96

This is concatenating two URLs.  I can't see any case where this would be a satisfactory implementation of whatever is supposed to happen here.  Note, I'm not even talking about the HAL specific handling here (I'm fine with that, since I'm using `traverson-hal` already).  I'm focusing completely on the concatenation of strings here.

I'm guessing what you really want to do is something like what is done here:

https://github.com/basti1302/traverson/blob/master/lib/transforms/resolve_next_url.js#L26

I suspect the two would be equivalent *if* the start URL had no path (e.g., `http://some.api.server.com/`).  But I'm using the library with an API root that has a path (e.g., `http://some.server.com/api') and now I'm seeing this issue.

If you could comment on the goal here, I could submit a PR.

**Comment by xogeny** [comment]
My comments in #22 could apply here as well.

**Comment by xogeny** [comment]
I *think* the solution is this:

https://github.com/basti1302/traverson/compare/master...xogeny:resolve

If you agree, let me know and I can submit it as a PR.  It passes all your existing tests.  It would be good to make tests for non-root level APIs.  I took a quick look at your test setup.  It seems easy enough to specify a different API root in the tests, but something has to be done on the `traverson-test-server` side, and I'm not exactly sure what.  Ideally, when setting up the `traverson-test-server`, it would be good to be able to specify the root of the API somehow (and then make the client test code consistent with that).  In this way, you could run the same set of tests for both a root level API and a non-root level API.  But again, I wasn't quite sure how to tweak the `traverson-test-server` module to allow this.

**Comment by basti1302** [comment]
I guess I wrote this under two assumptions:

* the hrefs in a HAL resource are absolute, but without host (that is, something like `/orders/123`)
* the start URL has no path

Which of course are bad assumptions. So please go ahead with your fix.

By the way, I already added you as a collaborator a while back (that is, you have commit access), so for a small change like this, you don't need a PR, you can just commit it to this repo, if you like.

Ping me when you have committed, I'll publish a new bugfix version then.

Thanks! <3

**Comment by basti1302** [comment]
I just realized that I didn't respond to the traverson-test-server part of your issue. I think it would be enough to have a few new tests that use a non-root level API instead of running *all* existing tests twice (once for a root level API and once again for a non-root level API), no? What do you think?

Also, only test/localhost.js uses traverson test server, most of the other tests mock the actual HTTP request/response stuff.

**Comment by basti1302** [comment]
What's the status on this? I'd like to include it in the next release. Would you rather have me pull the change from your repo instead of pushing it yourself? Or submit it as a pull request? Whatever is convenient for you.

**Comment by xogeny** [comment]
Go ahead and pull from my `resolve` branch.  I've been using it for a while, I think it is ok.  I'd submit a PR, but then I'd have to open another issue (as far as I know).  Probably simpler to just have you pull that branch in and avoid the clutter of opening another issue.

**Comment by basti1302** [comment]
Okay, I pulled from your branch.

**Comment by basti1302** [comment]
This has landed in 2.0.0.
