### ISSUE TITLE
Type error while evaluating JSONPath expression

### ISSUE THREAD

**Issue by Baiteman** [basti1302/traverson#43]
Hi,
thanks for this neat client. It might just come in very handy for our application which I would highly appreciate.

I came upon a somewhat unintelligible error which I'd like to share if you are interested.

If you use a JSONPath expression (like $._links.user instead of $._links.user.href) which points to an object instead to an object property you will produce this error:

    Uncaught TypeError: a.step.url.search is not a function

While it's not a big issue I spent some time brooding over it and I thought I should at least tell you about it so others might not have to make the same mistake.

To illustrate:

A call like this

    traverson.from('http://localhost:8090')
        .json()
		.follow('$._links.user')
        .getResource(function(err, resource){
            if(err){
                console.log(err);
                return;    
            }
            console.log(resource);        
        });

to an endpoint like this:

    {
    "_links" : {
      "ressource" : {
        "href" : "http://localhost:8090/ressource{?page,size,sort}",
        "templated" : true
      },
      "user" : {
        "href" : "http://localhost:8090/user{?page,size,sort}",
        "templated" : true
    }}}

will result in the aforementioned error. $._links.user points to an object and will fail weirdly while $._links.user.href will work fine.

**Comment by basti1302** [comment]
Thank you for taking the time to report this. A fix with a decent error message will be included in the next release. 

I'll probably not create a new release only for this fix, though.
