### ISSUE TITLE
Accessing response headers

### ISSUE THREAD

**Issue by mrdbeck** [basti1302/traverson#47]
Our Api is potentially returning a session cookie in the response header. This doesn't seem to be exposed by getResource. 

Is there some way to access the header?

**Comment by basti1302** [comment]
https://github.com/basti1302/traverson/blob/master/user-guide.markdown#more-control-receive-the-full-http-response-or-the-url

**Comment by mrdbeck** [comment]
RTFM Sorry

**Comment by basti1302** [comment]
No worries

Happy to help  :-)
