### ISSUE TITLE
How to set xhr.withCredentials?

### ISSUE THREAD

**Issue by ricardoecosta** [basti1302/traverson#48]
Hi guys, first of all, amazing work with this project!

What do I need to do to inject xhr.withCredentials? Any idea? I looked at the source code but I can't seem to find the connection between the request builder and the xhr object. Please help :)

**Comment by basti1302** [comment]
Currently there is no way to set this. Would make sense to have it. Would you like to take a shot at it?

**Comment by ricardoecosta** [comment]
Hi @basti1302 had a crack at it, hope all is fine, added tests and build is passing.

**Comment by basti1302** [comment]
This has landed in release 3.1.0
