### ISSUE TITLE
Traverson returns response with empty header

### ISSUE THREAD

**Issue by Aracki** [basti1302/traverson#51]
When i **_post_** request using traverson I get **201 (Object created)**. But in response I get, headers are empty, while in network tab I can see response have headers with Location etc.

Screenshot above showing response with _status code 201_, but with _header_ and _headers_ empty...

![123](https://cloud.githubusercontent.com/assets/6129986/11842108/cbcaf546-a401-11e5-9a62-67f7b441d17a.png)

**Comment by basti1302** [comment]
Thanks for creating this as a new issue. You did not yet answer the question I raised #44, so I'll repeat it here:

* What does the *server* actually send in its HTTP response? Traverson does not create the HTTP response itself, it just takes whatever the server sends and makes it available to your JavaScript code.

Please open the network tab in the chrome dev tools and try to find the HTTP request in question. Check the response tab and also the headers in the response.

If there is a response body and response headers coming from the server and Traverson somehow discards them, then this is a bug in Traverson. But maybe in your case the server really sends no body and no headers in the response?

**Comment by Aracki** [comment]
![5](https://cloud.githubusercontent.com/assets/6129986/11842424/dc510ce6-a403-11e5-9399-1f55fe81f8c8.png)

Response body is empty like it should be in my case, but headers have info like _Location_. Probably it's not traverson bug, maybe i'm missing something...

**Comment by basti1302** [comment]
Ah, sorry, I misread your post. You already said that you see the headers in the network tab, my bad. I'll look into it.

**Comment by basti1302** [comment]
Currently I don't think that this is a problem with Traverson, as I can not reproduce it when testing Traverson against a test server. You might be running into a CORS problem here, could be your server side needs to send 

```
Access-Control-Expose-Headers: Location
```

I just now remembered that I had the same problem with the traverson test server: The location header (and other headers) would appear in the network tab but are invisible to the JavaScript code.

Have a look here: https://github.com/visionmedia/superagent/issues/770#issuecomment-155555257

Feel free to reopen this if you come the conclusion that Traverson is the culprit. Also, feel free to comment if the `Access-Control-Expose-Headers` helped you.

**Comment by Aracki** [comment]
Thanks! Adding `Access-Control-Expose-Headers` in my _CORS_ filter helped! Now I can access ID of created object.

**Comment by basti1302** [comment]
You're welcome :dancers:
