### ISSUE TITLE
Promise native version of traverson

### ISSUE THREAD

**Issue by tsgautier** [basti1302/traverson#56]
I see that traverson-angular converts traverson's api's to promise native.  I want to use traverson in a node.js process, and don't have any need for angular.

Would it be possible for a traverson-promise plugin or something equivalent to support promises natively instead of callbacks?

**Comment by basti1302** [comment]
That would certainly be possible. I have no interest in writing or maintaining such a module, though. Do you? What I can offer is help to get it started.

**Comment by basti1302** [comment]
Closing as I consider this out of scope for this repo. Feel free to continue the discussion anyway.

**Comment by tsgautier** [comment]
I stole the code out of traverson-angular and made it work for me locally.  I'm willing to create a new module.

**Comment by basti1302** [comment]
Great news! If you'd publish this as a module, that would be splendid - people have asked for this before and I'm sure it will find its users. Do you want to keep it in your account? I've been also thinking about creating a traverson organization here on GitHub and move all Traverson related repositories from my account there, this could also be the home for the traverson-as-promise repo.

Of course it is your call, whatever you prefer.
