### ISSUE TITLE
Error: Links must be objects, not string

### ISSUE THREAD

**Issue by ashishpatel17** [basti1302/traverson#63]
Whenever we give any path in follow() in getResource() function it always shows the Error: Links must be objects, not string what does it mean.

**Comment by basti1302** [comment]
Could you please give a few more details, including:
* your code, that is, how are you using traverson?
* which version of Traverson you are using?
* are you using it in the browser or in Node.js?
* a detailed stack trace.

If I would have to guess from what little inforḿation has been provided and checking the relevant places in the code, I could imagine that you are passing something that is *not* of type string to the `follow()` method (that is, something like a `number` or `boolean`.

**Comment by basti1302** [comment]
Closing due to lack of information.
