### ISSUE TITLE
`requestOptions` removes functions options

### ISSUE THREAD

**Issue by JulienYo** [basti1302/traverson#65]
Hello,

I need to define a `jsonReplacer` to request, but unfortunately it's a function option which is removed by `traverson/lib/merge_recursive.js` `merge` function.

Any reason to specifically removing functions properties in the `merge` function ?

**Comment by basti1302** [comment]
This definitely sounds like a bug. I'll look into it. Thing is, I'm on vacation right now, it might be a while until I can do so.

**Comment by JulienYo** [comment]
Hello,

Thanks for taking a look so quickly on this (while on vacation!)

It fixes the `requestOption.jsonReplacer` to be taken into account ...

But I had to open #68 for being applied :smiley:

**Comment by basti1302** [comment]
fix has landed in release 3.2.0
