### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by BrunoQuaresma** [basti1302/traverson#92]
Do you use caching to avoid excessive requests?

**Comment by basti1302** [comment]
Traverson does no caching on its own. If you use Traverson in the browser, the browser runtime implements caching according to the HTTP spec, assuming your backend sets caching headers (max-age etc.). If you use Traverson in Node.js, there will be no caching. This has been discussed before, my stance here is that implementing the HTTP caching rules is outside of the scope of Traverson. Ideally, this would be solved in request/request (which Traverson uses when running on Node.js) but they have decided to not include caching directly in their core module. 

There are some solutions out there to do caching with request and there is also a lot of discussion around caching in the request repository, see https://github.com/request/request/search?q=cache&type=Issues

I guess you could realize caching right now, for example by using https://github.com/gitterHQ/request-http-cache/ -- I didn't try myself, though.

If you find a good solution for the Node.js, feel free to report back :) . It would be nice to include an example in the docs.

**Comment by BrunoQuaresma** [comment]
Thanks!
